### ISSUE TITLE
Blueprint Todo #1

### ISSUE THREAD

**Issue by yooksi** [barrowisp/craftastrophe#26]
- [x] Rename all issues to start with a capital letter.
- [x] Rename ```datasheet``` words to ```blueprint``` in all issues
- [x] Create Github project for blueprints.
- [x] Move all relevant issue cards to that project.
- [x] Create binder item texture.

**Comment by yooksi** [comment]
@barrowisp After you complete each task, tick the checkbox to mark that that task is complete. Once all of the tasks are completed, close the issue with a celebratory comment.

**Comment by barrowisp** [comment]
All cards seem to now be assigned to Projects
